version: "3.8"

networks:
  grafana:

services:
  log-generator:
    image: sikwan/random-json-logger:latest
    container_name: log-generator
    restart: always
    networks:
      - grafana

  #uptime-kuma:
  #  image: louislam/uptime-kuma:1
  #  container_name: uptime-kuma
  #  volumes:
  #    - ./uptime-kuma-data:/app/data
  #  ports:
  #    - 3001:3001  # <Host Port>:<Container Port>
  #  restart: always

  agent:
    image: grafana/agent:v0.40.3
    container_name: agent
    volumes:
      - ./agent/gf-docker-integration.river:/etc/agent-config
      - /var/run/docker.sock:/var/run/docker.sock
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    entrypoint:
      - /bin/grafana-agent 
      - run 
      #  Makes sure the debugging UI is available outside of the Docker container
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/agent-config
    privileged: true
    devices:
      - "/dev/kmsg"
    environment:
      AGENT_MODE: flow
    ports:
      - "12345:12345"
    networks:
      - grafana

  nvidia_smi_exporter:
    image: utkuozdemir/nvidia_gpu_exporter:1.1.0
    container_name: nvidia_smi_exporter
    restart: unless-stopped
    devices:
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia0:/dev/nvidia0
    volumes:
      - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so
      - /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
      - /usr/bin/nvidia-smi:/usr/bin/nvidia-smi
    ports:
      - "9835:9835"
    networks:
      - grafana
