version: "3.8"

x-loki: &loki
  image: grafana/loki:v0.4.0
  volumes:
    - ./loki-values.yaml:/config
  restart: always
  entrypoint:
    - /bin/loki
    - -config.file=/config/loki-values.yaml 
    - -target=$$LOKI_TARGET
  networks:
    - grafana

networks:
  grafana:

volumes:
  chunks:
  index:

services:
  grafana:
    image: grafana/grafana:10.0.8
    restart: always
    ports:
      - "3000:3000"
    networks:
      - grafana

  agent:
    image: grafana/agent:main-9a53c48
    volumes:
      - ./agent-config.river:/etc/agent-config
    restart: always
    entrypoint:
      - /bin/grafana-agent
      #  Makes sure the debugging UI is available outside of the Docker container
      - -server.http.address=0.0.0.0:12345
      - -config.file=/etc/agent-config/agent-config.river
    environment:
      HOSTNAME: agent
      AGENT_MODE: flow
      #REMOTE_WRITE_HOST: mimir:9009
      LOKI_HOST: loki:3100
      #TEMPO_HOST: tempo:4317
    ports:
      - "12345:12345"
    networks:
      - grafana
    depends_on:
      - grafana
      - loki
    
  loki-distributor:
    <<: *loki
    environment:
      LOKI_TARGET: distributor

  loki-ingester:
    <<: *loki
    environment:
      LOKI_TARGET: ingester

  loki-querier:
    <<: *loki
    environment:
      LOKI_TARGET: querier
