version: "3.8"

networks:
  grafana:

services:
  log-generator:
    image: sikwan/random-json-logger:latest
    container_name: log-generator
    restart: always
    networks:
      - grafana

  agent:
    image: grafana/agent:latest
    container_name: agent
    volumes:
      - ./agent/config.river:/etc/agent-config
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - /bin/grafana-agent 
      - run 
      #  Makes sure the debugging UI is available outside of the Docker container
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/agent-config
    environment:
      AGENT_MODE: flow
    ports:
      - "12345:12345"
    networks:
      - grafana
