version: "3.8"

networks:
  grafana:

services:
  agent:
    image: grafana/agent:v0.37.4
    container_name: agent
    volumes:
      - ./agent/gf-docker-integration.river:/etc/agent-config
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - /bin/grafana-agent 
      - run 
      #  Makes sure the debugging UI is available outside of the Docker container
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/agent-config
    environment:
      AGENT_MODE: flow
    ports:
      - "12345:12345"
    networks:
      - grafana
