auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  http_server_read_timeout: 600s
  http_server_write_timeout: 600s
  log_level: info

common:
  ring:
    kvstore:
      store: memberlist
  replication_factor: 1

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist

compactor:
  # Directory where files can be downloaded for compaction.
  working_directory: /data/retention
  # The shared store used for storing boltdb files.
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  # This specifies a delay after which chunks that meet the retention criteria (which should be 90d) will be fully deleted.
  retention_delete_delay: 2h

schema_config:
  configs:
    # A from value marks the starting point of that schema. 
    # The schema is active until another entry defines a new schema with a new from date.
    - from: 2023-01-11
      # store and object_store below affect which <storage_config> key is used. Which index to use. 
      # Either tsdb or boltdb-shipper.
      store: boltdb-shipper
      # Which store from the storage_config to use for the chunks
      object_store: filesystem
      schema: v12
      index:
        prefix: loki_index_
        # period must be <=24h see https://grafana.com/docs/loki/latest/operations/storage/retention/
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /data/index
    cache_location: /data/boltdb-cache
    shared_store: filesystem
  filesystem:
    directory: /tmp/loki/

# delete old logs after 90 days
limits_config:
  retention_period: 2160h
  query_timeout: 1m
