auth_enabled: true

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  http_server_read_timeout: 600s
  http_server_write_timeout: 600s

ruler:
  storage:
    type: local
    local:
      directory: /etc/loki/rules
  ring:
    kvstore:
      store: memberlist
  enable_alertmanager_v2: true
  enable_api: true
  alertmanager_url: http://{{ .Values.mimir_endpoint }}/alertmanager

compactor:
  # Directory where files can be downloaded for compaction.
  working_directory: /data/retention
  # The shared store used for storing boltdb files.
  shared_store: gcs
  compaction_interval: 10m
  retention_enabled: true
  # This specifies a delay after which chunks that meet the retention criteria (which should be 90d) will be fully deleted.
  retention_delete_delay: 2h

schema_config:
  configs:
    # A from value marks the starting point of that schema. 
    # The schema is active until another entry defines a new schema with a new from date.
    - from: 2023-01-11
      # store and object_store below affect which <storage_config> key is used. Which index to use. 
      # Either tsdb or boltdb-shipper.
      store: boltdb-shipper
      # Which store from the storage_config to use for the chunks
      object_store: gcs
      schema: v12
      index:
        prefix: loki_index_
        # period must be <=24h see https://grafana.com/docs/loki/latest/operations/storage/retention/
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /data/index
    cache_location: /data/boltdb-cache
    shared_store: gcs
  gcs:
    bucket_name: tolmac-loki
    chunk_buffer_size: 0
    request_timeout: "3s"
    enable_http2: true

# delete old logs after 90 days
limits_config:
  retention_period: 2160h
  query_timeout: 1m
